# Generated by Django 4.2 on 2024-02-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_explorer', '0002_rename_favorite_favoritemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemodel',
            name='imageURL',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='favoritemodel',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
